FROM www.nsl.tuis.ac.jp:5000/jupyterhub-ltictr/jupyter-singleuser

USER root

ADD  \
     bin/ipynb_extract \
     bin/extract \
     bin/ipynb_tocsv \
     bin/tocsv \
     /usr/local/bin/

RUN  chmod a+rx /usr/local/bin/* \
  && true

